- hosts: localhost
  gather_facts: no
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Install Zsh with dependencies are installed
      apt:
        name: "{{ ['zsh'] + zsh_dependencies }}"
        state: present
        update_cache: yes
      become: true
      vars:
        zsh_dependencies: []
    - name: Ensure zsh is the default shell
      user:
        name: "{{ ansible_user }}"
        shell: "/usr/bin/zsh"
      become: true
    - name: Download Oh My Zsh installation script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "/tmp/install_ohmyzsh.sh"
    - name: Run Oh My Zsh installation script
      command: sh /tmp/install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"
