bin:
  link: "~/.local/bin"

fzf:
  link: []
  dependencies:
    - fzf

tmux:
  link: []
  dependencies:
    - tmux

gdb:
  link: [{".gdbinit": "~"}]
  dependencies:
    - gdb

lunarvim:
#   prelink:
#     # - bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install-neovim-from-release)
      # - bash <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh)
#     - bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) -y
  link: "~/.config/lvim"
#   dependencies:
#     - git
#     - make
#     - pip
#     - npm
#     - nodejs
#     - cargo
#   postlink:
#     - go install github.com/jesseduffield/lazygit@latest
#     - do I need to move go folder somewhere?


system:
  link: "~"
  dependencies:
    - zsh
    - ripgrep
  postlink:
    - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
    - source ~/.zshrc
